global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-go'
    static_configs:
      - targets: ['api-go:8080']

  - job_name: 'api-python'
    static_configs:
      - targets: ['api-python:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
